# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
arr = np.array(10)

3. Create a vector with values ranging from 10 to 49

In [8]:
arr1 = np.arange(10,50)

4. Find the shape of previous array in question 3

In [10]:
print(np.shape(arr1))

(40,)


5. Print the type of the previous array in question 3

In [14]:
print(arr1.dtype)

int32


6. Print the numpy version and the configuration


In [15]:
print(np.__version__)

1.18.1


7. Print the dimension of the array in question 3


In [16]:
print(arr1.ndim)

1


8. Create a boolean array with all the True values

In [20]:
arr2 = np.arange(1,11)
bool_arr = arr2 > 0.5 
print(bool_arr)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [22]:
arr3 = np.arange(1,5).reshape(2,2)
print(arr3)

[[1 2]
 [3 4]]


10. Create a three dimensional array



In [23]:
arr4 = np.arange(1,10).reshape(3,3)
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [24]:
rev = np.flip(arr1,0)
print(rev)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [25]:
null = np.zeros(10)
null[4] = 1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [27]:
id = np.identity(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [29]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(float)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [33]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
mul = arr1*arr2
print(mul)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [37]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr = np.array([arr1 == arr2])
print(arr)

[[[False False False]
  [False False False]]]


17. Extract all odd numbers from arr with values(0-9)

In [39]:
arr = np.arange(0,10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [40]:
arr = np.arange(0,10)
arr[arr%2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [53]:
arr = np.arange(10)
arr[5:9] =12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [7]:
arr2D = np.array([[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]])
arr2D

2


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [11]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[(1,1)] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [16]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d[(0,0)] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [26]:
array2d = np.arange(0,10).reshape(2,5)
print(array2d[(0,)])

[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [29]:
array2d = np.arange(0,10).reshape(2,5)
print(array2d[(1,1)])

6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [33]:
array2d = np.arange(0,10).reshape(2,5)
print(array2d[:,2])

[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [39]:
Rarray = np.random.randn(10*10)
print("Maximum: ",np.max(Rarray))
print("Minimum: ",np.min(Rarray))

Maximum:  2.7654682882063293
Minimum:  -2.2498595478725973


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [45]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a [a == b])

[2 2 4 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [46]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a==b

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[(names != "Will")])

[[-0.29622769  0.81888094  1.62798549  0.30734896]
 [ 0.27516497 -1.82102806  0.78740506 -0.18781586]
 [ 0.07404431  0.53764544 -1.00053857  1.8163478 ]
 [ 0.12753797  1.3881624   0.41448036 -1.21909092]
 [ 1.10747994 -1.26036527  0.63073585 -1.06604791]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [52]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[((names != "Will") & (names != "Joe"))])

[[-0.56874358  0.606297    0.86608126 -1.53931039]
 [ 1.73180415 -0.24430739 -1.11789606  0.18606635]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [62]:
ar2d = np.random.randn(1,15).reshape(5,3)
ar2d

array([[ 0.15859286,  1.41518449,  0.08088331],
       [-2.88538142, -0.10578827,  1.79898788],
       [-1.20403617,  0.7414701 , -0.4697686 ],
       [-1.5028709 ,  1.16162142, -0.39959851],
       [ 1.06398832, -0.52222436,  1.01939928]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [63]:
ar = np.random.randn(1,16).reshape(2,2,4)
ar

array([[[ 0.09115622,  0.45118917,  0.18309536, -1.07203252],
        [ 1.18715543, -2.46759227, -1.08481377, -0.10365432]],

       [[-0.53014526, -1.30945572,  0.79161927, -1.14180085],
        [-0.2018525 , -2.07233282,  0.0562005 ,  0.25542197]]])

33. Swap axes of the array you created in Question 32

In [64]:
print(np.transpose(ar))

[[[ 0.09115622 -0.53014526]
  [ 1.18715543 -0.2018525 ]]

 [[ 0.45118917 -1.30945572]
  [-2.46759227 -2.07233282]]

 [[ 0.18309536  0.79161927]
  [-1.08481377  0.0562005 ]]

 [[-1.07203252 -1.14180085]
  [-0.10365432  0.25542197]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [80]:
array = np.arange(1,11)
array = np.sqrt(array)
array[array<0.5] = 0
array

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [93]:
ar1 = np.random.randn(12)
ar2 = np.random.randn(12)
print(np.where(ar1>ar2,ar1,ar2))

[ 0.82570498  0.6054975   0.08820897  2.23789515  0.61304673 -0.83997446
  0.43671634 -0.95112718 -0.17646049  1.25782613  2.24934606  1.11546966]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [97]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(np.sort(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [114]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a = a[a != 5]
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [118]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[1] = newColumn
print(sampleArray)

[[34 43 73]
 [10 10 10]
 [53 94 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [119]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x.dot(y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [120]:
rArray = np.random.randn(20)
print(np.cumsum(rArray))

[ 2.41099447  2.64656153  1.84984928  0.30092907  0.69614509  1.13832034
  0.51009466 -0.09814743 -0.82188264  0.22706633  0.51234087  0.09201004
 -2.17661199 -3.32902787 -3.07975175 -3.57177364 -2.72356803 -2.50682366
 -4.12494522 -4.20257836]
