# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
import numpy as np
arr1D = np.arange(0,10)
arr2D = arr1D.reshape(2,5)
print(arr2D)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [10]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.ones((2,5))
print(np.concatenate((arr1,arr2),axis=0))

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [11]:
arr1 = np.arange(0,10).reshape(2,5)
arr2 = np.ones((2,5))
print(np.concatenate((arr1,arr2),axis=1))

[[0. 1. 2. 3. 4. 1. 1. 1. 1. 1.]
 [5. 6. 7. 8. 9. 1. 1. 1. 1. 1.]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [14]:
arr2D = np.arange(0,10).reshape(2,5)
arr1D = arr2D.ravel()
arr1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [20]:
arr2D = np.arange(0,15).reshape(5,3)
arr1D = arr2D.flatten()
arr2D

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [21]:
arr1D = np.arange(0,15)
arr2D = arr1D.reshape(5,3)
arr2D

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [28]:
arr = np.arange(0,25).reshape(5,5)
arrSqr = np.square(arr)
arrSqr

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [30]:
arr = np.arange(0,30).reshape(5,6)
arrMean = np.mean(arr)
arrMean

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [31]:
arr = np.arange(0,30).reshape(5,6)
print(np.std(arr))

8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [34]:
print(np.median(np.sort(arr)))

14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [36]:
print(np.transpose(arr))

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [38]:
x = np.arange(0,16).reshape(4,4)
print(np.trace(x))

30


## Question:13

### Find the determinant of the previous array in Q12?

In [41]:
print(np.linalg.det(x))

0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [43]:
y = np.random.randn(3,3)
print("5th Percentile: ",np.percentile(y, 5,0))
print("\n95th Percentile: ",np.percentile(y, 95,0))

5th Percentile:  [-1.54541567 -0.58042917 -1.20592895]

95th Percentile:  [ 0.0456012  -0.10792406 -0.08812888]


## Question:15

### How to find if a given array has any null values?

In [56]:
z = np.array([0,1,2,3,4,0,1,2,3,4])
print(np.any(z==0))


True
